export { prisma } from "./client";
export { PrismaClient, Prisma } from "@prisma/client";
export type { ProductKind, ProductStatus, DiscountType, CourseStatus, LeadFormStatus, CommunityStatus } from "@prisma/client";
export {
  upsertProfile,
  getTenantByOwnerId,
  setTenantStateCode,
  setStoreAnnouncement,
  getTenantByUsername,
  isUsernameTaken,
  createTenantForOwner,
  isTenantSuspended,
  getOnboardingStatus,
  type CreateTenantResult,
  type OnboardingStatus,
} from "./tenant";
export {
  listPlans,
  listActivePlans,
  getPlanById,
  getPlanByKey,
  createPlan,
  updatePlan,
  setPlanActive,
  planAllowsCustomDomain,
  listPricingSettings,
  getPricingSetting,
  upsertPricingSetting,
  type PlanInput,
  type CreatePlanResult,
} from "./pricing";
export {
  getSubscriptionByTenant,
  createPlatformOrder,
  getPlatformOrderByRazorpayId,
  markPlatformOrderPaid,
  activateFreePlan,
  claimPaymentEvent,
  markPaymentEventProcessed,
  recordPaymentEventError,
  countUnprocessedEvents,
  type PaidOrderResult,
} from "./subscription";
export {
  getWalletByTenant,
  getWalletStatus,
  ensureWallet,
  listWalletTransactions,
  debitWallet,
  type DebitResult,
} from "./wallet";
export {
  getSellerGateway,
  connectSellerGateway,
  disconnectSellerGateway,
} from "./gateway";
export {
  getSellerUpi,
  getEnabledSellerUpi,
  upsertSellerUpi,
  deleteSellerUpi,
} from "./upi";
export {
  createPaymentPage,
  listPaymentPages,
  getPaymentPageById,
  getActivePaymentPage,
  getActivePaymentPageById,
  updatePaymentPage,
  setPaymentPageActive,
  getCommissionBpsForTenant,
  createBuyerPayment,
  createCartOrder,
  getBuyerPaymentByOrderId,
  markBuyerPaymentPaid,
  confirmManualBuyerPayment,
  createUpiSession,
  expireStaleUpiOrders,
  isUpiAutoConfirmBlocked,
  autoConfirmOrHoldUpiOrder,
  cancelManualUpiOrder,
  settleDueCommissions,
  listTenantOrders,
  countTenantOrders,
  listPendingUpiOrders,
  listAbandonedCheckouts,
  countAbandonedCheckouts,
  listSoldOutProductsForOrder,
  getTenantSalesSummary,
  updateOrderFulfillment,
  setOrderFulfillmentStatus,
  getRefundableOrder,
  recordRefund,
  type CreatePageResult,
  type BuyerPaidResult,
  type UpiSessionResult,
  type UpiSubmitResult,
  type CancelUpiResult,
  type SalesSummary,
  type RefundResult,
  type OrderListOpts,
  type FulfillmentStatusFilter,
} from "./payments";
export {
  ensureBuyerAccount,
  listBuyerOrders,
  listBuyerDeliverables,
  getBuyerOrder,
} from "./buyer";
export {
  issuePlatformInvoices,
  listInvoices,
  getInvoice,
} from "./invoice";
export {
  PLATFORM_SETTING_KEYS,
  UPI_DUE_BLOCK_DEFAULT_PAISE,
  getPlatformSettings,
  getBranding,
  getUpiDueBlockPaise,
  upsertPlatformSettings,
  type PlatformSettingKey,
  type PlatformSettings,
} from "./settings";
export {
  getTenantTracking,
  upsertTenantTracking,
} from "./tracking";
export {
  notifyTenant,
  listNotifications,
  countUnreadNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  recordNotificationLog,
  listNotificationLogs,
  getOrderNotifyContext,
} from "./notifications";
export {
  listNotificationTemplates,
  upsertNotificationTemplate,
  getNotificationPreferences,
  setNotificationPreference,
  getEmailDispatchConfig,
} from "./notif-config";
export {
  normalizeDomain,
  addDomain,
  listDomains,
  getDomainById,
  deleteDomain,
  markDomainVerified,
  getTenantByCustomDomain,
  setPrimaryDomain,
  getPrimaryDomain,
  type AddDomainResult,
  type VerifyDomainResult,
  type SetPrimaryResult,
} from "./domains";
export {
  createAbuseReport,
  listAbuseReports,
  countOpenAbuseReports,
  reviewAbuseReport,
} from "./abuse";
export {
  refreshRiskAlerts,
  listRiskAlerts,
  countOpenRiskAlerts,
  dismissRiskAlert,
} from "./risk";
export {
  createCommunity,
  listCommunities,
  getCommunityById,
  updateCommunity,
  setCommunityStatus,
  listCommunityPosts,
  createCommunityPost,
  deleteCommunityPost,
  listPublishedCommunities,
  getPublishedCommunity,
  getPublishedCommunityById,
  getPublishedCommunityMeta,
  getMembership,
  listJoinedCommunities,
  joinFreeCommunity,
  type CreateCommunityResult,
} from "./community";
export {
  createProduct,
  listProducts,
  getProductById,
  listPublishedProducts,
  getPublishedProduct,
  getPublishedProductById,
  listPublishedProductsByIds,
  updateProduct,
  setProductStatus,
  getProductSalesCounts,
  getOrderBumpProduct,
  type CreateProductResult,
} from "./products";
export {
  createCoupon,
  listCoupons,
  getCouponById,
  updateCoupon,
  setCouponActive,
  deleteCoupon,
  applyCoupon,
  type CouponInput,
  type CreateCouponResult,
  type ApplyCouponResult,
} from "./coupons";
export {
  createCourse,
  listCourses,
  getCourseById,
  updateCourse,
  setCourseStatus,
  listLessons,
  getLesson,
  createLesson,
  updateLesson,
  deleteLesson,
  listPublishedCourses,
  getPublishedCourse,
  getPublishedCourseById,
  getPublishedCourseMeta,
  getEnrolment,
  listEnrolledCourses,
  type CreateCourseResult,
} from "./courses";
export {
  chargeAndCreateAiPage,
  createAiPage,
  setAiPageChargeRef,
  listAiPages,
  getPublishedAiPage,
  getAiPageForOwner,
  updateAiPageContent,
  recordAiPageVersion,
  listAiPageVersions,
  getAiPageVersion,
  setAiPagePublished,
  deleteAiPage,
  type ChargeCreateResult,
  type CreateAiPageResult,
} from "./aipage";
export {
  getFeatureRule,
  listFeatureRules,
  upsertFeatureRule,
  setPlanFeatureLimit,
  listPlanFeatureLimits,
  getFeatureUsage,
  getFeatureQuota,
  getTenantFeatureUsageSummary,
  consumeFeature,
  type ConsumeResult,
  type FeatureQuota,
  type FeatureUsageRow,
} from "./feature";
export {
  getPlatformOverview,
  listTenantsAdmin,
  getTenantAdminDetail,
  setTenantSuspended,
  adminAdjustWallet,
  markChargeback,
  listAdminAuditLog,
  getRevenueReport,
  getWalletAttention,
  searchBuyerPayments,
  listRecentPaymentEvents,
  type PlatformOverview,
  type AdminWalletResult,
  type RevenueReport,
  type AttentionRow,
} from "./admin";

export {
  createLeadForm,
  listLeadForms,
  getLeadFormById,
  getPublishedLeadForm,
  updateLeadForm,
  setLeadFormStatus,
  submitLead,
  listLeadSubmissions,
  countLeadSubmissions,
  type CreateLeadFormResult,
  type LeadFormInput,
} from "./leadforms";

export { listContacts, type CrmContact } from "./crm";

export {
  getBioLink,
  getPublishedBioLink,
  upsertBioLink,
  recordBioLinkClick,
  getBioLinkClickStats,
  type BioLinkInput,
  type BioClickStat,
} from "./biolink";

export {
  getAnalytics,
  recordPageView,
  getTrafficAnalytics,
  type AnalyticsResult,
  type AnalyticsDay,
  type TrafficResult,
} from "./analytics";
export { logActivity, listActivityLog } from "./activity";
export {
  createProductReview,
  getBuyerReviewForProduct,
  getProductReviews,
  getProductRatingSummary,
  getProductRatingSummaries,
  createCourseReview,
  getBuyerReviewForCourse,
  getCourseReviews,
  getCourseRatingSummary,
  listTenantReviews,
  setReviewStatus,
  type CreateReviewResult,
  type RatingSummary,
} from "./reviews";
