export { prisma } from "./client";
export { PrismaClient, Prisma } from "@prisma/client";
export type { ProductKind, ProductStatus, DiscountType, CourseStatus, LeadFormStatus, CommunityStatus } from "@prisma/client";
export {
  upsertProfile,
  getTenantByOwnerId,
  setTenantStateCode,
  setStoreAnnouncement,
  setStorefrontBranding,
  type StorefrontBrandingInput,
  getTenantByUsername,
  isUsernameTaken,
  createTenantForOwner,
  isTenantSuspended,
  getOnboardingStatus,
  type CreateTenantResult,
  type OnboardingStatus,
} from "./tenant";
export {
  listPlans,
  listActivePlans,
  getPlanById,
  getPlanByKey,
  createPlan,
  updatePlan,
  setPlanActive,
  planAllowsCustomDomain,
  listPricingSettings,
  getPricingSetting,
  upsertPricingSetting,
  type PlanInput,
  type CreatePlanResult,
} from "./pricing";
export {
  getSubscriptionByTenant,
  createPlatformOrder,
  getPlatformOrderByRazorpayId,
  markPlatformOrderPaid,
  activateFreePlan,
  claimPaymentEvent,
  markPaymentEventProcessed,
  recordPaymentEventError,
  countUnprocessedEvents,
  type PaidOrderResult,
} from "./subscription";
export {
  getWalletByTenant,
  getWalletStatus,
  ensureWallet,
  listWalletTransactions,
  debitWallet,
  type DebitResult,
} from "./wallet";
export {
  getSellerGateway,
  connectSellerGateway,
  disconnectSellerGateway,
} from "./gateway";
export {
  getSellerUpi,
  getEnabledSellerUpi,
  upsertSellerUpi,
  deleteSellerUpi,
} from "./upi";
export {
  createPaymentPage,
  listPaymentPages,
  countPaymentPages,
  getPaymentPageById,
  getActivePaymentPage,
  getActivePaymentPageById,
  updatePaymentPage,
  setPaymentPageActive,
  getCommissionBpsForTenant,
  createBuyerPayment,
  createCartOrder,
  getBuyerPaymentByOrderId,
  markBuyerPaymentPaid,
  confirmManualBuyerPayment,
  createUpiSession,
  expireStaleUpiOrders,
  isUpiAutoConfirmBlocked,
  autoConfirmOrHoldUpiOrder,
  cancelManualUpiOrder,
  settleDueCommissions,
  listTenantOrders,
  countTenantOrders,
  listPendingUpiOrders,
  listAbandonedCheckouts,
  countAbandonedCheckouts,
  listCheckoutsForRecovery,
  claimRecoveryEmail,
  listSoldOutProductsForOrder,
  getTenantSalesSummary,
  updateOrderFulfillment,
  setOrderFulfillmentStatus,
  getRefundableOrder,
  recordRefund,
  type CreatePageResult,
  type BuyerPaidResult,
  type UpiSessionResult,
  type UpiSubmitResult,
  type CancelUpiResult,
  type SalesSummary,
  type RefundResult,
  type OrderListOpts,
  type FulfillmentStatusFilter,
} from "./payments";
export {
  ensureBuyerAccount,
  listBuyerOrders,
  listBuyerDeliverables,
  getBuyerOrder,
} from "./buyer";
export {
  issuePlatformInvoices,
  listInvoices,
  getInvoice,
} from "./invoice";
export {
  PLATFORM_SETTING_KEYS,
  UPI_DUE_BLOCK_DEFAULT_PAISE,
  getPlatformSettings,
  getBranding,
  getUpiDueBlockPaise,
  upsertPlatformSettings,
  type PlatformSettingKey,
  type PlatformSettings,
} from "./settings";
export {
  getTenantTracking,
  upsertTenantTracking,
} from "./tracking";
export {
  socialProofName,
  listRecentSocialProof,
  type SocialProofEvent,
} from "./social-proof";
export {
  createExperiment,
  listExperiments,
  getExperimentById,
  getRunningExperimentForPage,
  stopExperiment,
  deleteExperiment,
  incrementExperiment,
  listPagesForExperiment,
  type ExperimentVariant,
  type CreateExperimentResult,
} from "./experiments";
export type { ExperimentStatus } from "@prisma/client";
export {
  canBuyerAccess,
  createSupportTicket,
  listBuyerTickets,
  getBuyerTicket,
  addBuyerReply,
  listSellerTickets,
  countOpenTickets,
  getSellerTicket,
  addSellerReply,
  setTicketStatus,
  type BuyerIdentity,
} from "./support";
export type { SupportTicketStatus, SupportSender } from "@prisma/client";
export {
  createSite,
  listSites,
  getSiteWithPages,
  renameSite,
  deleteSite,
  assignPageToSite,
  getSiteNav,
  type SiteNavItem,
} from "./sites";
export {
  createBuilderTemplate,
  listBuilderTemplates,
  getBuilderTemplate,
  updateBuilderTemplate,
  deleteBuilderTemplate,
  listPublishedTemplates,
  getPublishedTemplate,
  type BuilderTemplateInput,
} from "./templates";
export {
  getPublishedCoursesByIds,
  getActivePaymentPagesByIds,
  getPublishedLeadFormsByIds,
} from "./builder-entities";
export {
  notifyTenant,
  listNotifications,
  countNotifications,
  countUnreadNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  recordNotificationLog,
  listNotificationLogs,
  getOrderNotifyContext,
} from "./notifications";
export {
  listNotificationTemplates,
  upsertNotificationTemplate,
  getNotificationPreferences,
  setNotificationPreference,
  getEmailDispatchConfig,
} from "./notif-config";
export {
  normalizeDomain,
  addDomain,
  listDomains,
  getDomainById,
  deleteDomain,
  markDomainVerified,
  getTenantByCustomDomain,
  setPrimaryDomain,
  getPrimaryDomain,
  type AddDomainResult,
  type VerifyDomainResult,
  type SetPrimaryResult,
} from "./domains";
export {
  createAbuseReport,
  listAbuseReports,
  countOpenAbuseReports,
  countAbuseReports,
  reviewAbuseReport,
} from "./abuse";
export {
  refreshRiskAlerts,
  listRiskAlerts,
  countOpenRiskAlerts,
  dismissRiskAlert,
} from "./risk";
export {
  getVerification,
  submitVerification,
  reviewVerification,
  listPendingVerifications,
  countPendingVerifications,
  addKycDocument,
  listKycDocuments,
  getKycDocument,
  deleteKycDocument,
  isKycDocType,
  type KycDocType,
} from "./verification";
export type { VerificationStatus } from "@prisma/client";
export {
  createCommunity,
  listCommunities,
  countCommunities,
  getCommunityById,
  updateCommunity,
  setCommunityStatus,
  listCommunityPosts,
  createCommunityPost,
  deleteCommunityPost,
  listPublishedCommunities,
  getPublishedCommunity,
  getPublishedCommunityById,
  getPublishedCommunityMeta,
  getMembership,
  listJoinedCommunities,
  joinFreeCommunity,
  listCommunityMessages,
  createCommunityMessage,
  deleteOwnCommunityMessage,
  setCommunityMessageStatus,
  deleteCommunityMessageAsSeller,
  type CreateCommunityResult,
  type CommunityMessageNode,
  type CreateCommunityMessageResult,
} from "./community";
export type { CommunityMessageStatus } from "@prisma/client";
export {
  createProduct,
  listProducts,
  countProducts,
  getProductById,
  listPublishedProducts,
  getPublishedProduct,
  getPublishedProductById,
  listPublishedProductsByIds,
  updateProduct,
  setProductStatus,
  getProductSalesCounts,
  getStoreAnalytics,
  getOrderBumpProduct,
  listCollections,
  listPublishedCollections,
  createCollection,
  renameCollection,
  deleteCollection,
  listProductVariants,
  createVariant,
  deleteVariant,
  variantsByProductIds,
  type CreateProductResult,
} from "./products";
export {
  createCoupon,
  listCoupons,
  countCoupons,
  getCouponById,
  updateCoupon,
  setCouponActive,
  deleteCoupon,
  applyCoupon,
  getCouponStats,
  type CouponInput,
  type CreateCouponResult,
  type ApplyCouponResult,
  type ApplyCouponContext,
  type CouponStat,
} from "./coupons";
export {
  createCourse,
  listCourses,
  countCourses,
  getCourseById,
  updateCourse,
  setCourseStatus,
  listLessons,
  getLesson,
  createLesson,
  updateLesson,
  deleteLesson,
  listPublishedCourses,
  getPublishedCourse,
  getPublishedCourseById,
  getPublishedCourseMeta,
  getEnrolment,
  listEnrolledCourses,
  getCourseEnrolmentStats,
  getCourseAnalytics,
  toggleLessonProgress,
  getCourseProgress,
  listCourseSections,
  createSection,
  renameSection,
  deleteSection,
  groupLessonsBySection,
  listCourseStudents,
  type CreateCourseResult,
  type CourseStudent,
} from "./courses";
export {
  chargeAndCreateAiPage,
  createAiPage,
  setAiPageChargeRef,
  listAiPages,
  getPublishedAiPage,
  getAiPageForOwner,
  updateAiPageContent,
  renameAiPage,
  recordAiPageVersion,
  listAiPageVersions,
  getAiPageVersion,
  setAiPagePublished,
  deleteAiPage,
  type ChargeCreateResult,
  type CreateAiPageResult,
} from "./aipage";
export {
  getFeatureRule,
  listFeatureRules,
  upsertFeatureRule,
  setPlanFeatureLimit,
  listPlanFeatureLimits,
  getFeatureUsage,
  getFeatureQuota,
  getTenantFeatureUsageSummary,
  consumeFeature,
  listFeatureCharges,
  countFeatureCharges,
  sumFeatureChargesPaise,
  availableFeatureCreditsByKey,
  type ConsumeResult,
  type FeatureQuota,
  type FeatureUsageRow,
  type FeatureChargeRow,
} from "./feature";
export {
  getPlatformOverview,
  listTenantsAdmin,
  countTenantsAdmin,
  getTenantAdminDetail,
  setTenantSuspended,
  adminAdjustWallet,
  markChargeback,
  listAdminAuditLog,
  listGlobalAdminAuditLog,
  getRevenueReport,
  getWalletAttention,
  searchBuyerPayments,
  countBuyerPaymentsSearch,
  listRecentPaymentEvents,
  type PlatformOverview,
  type AdminWalletResult,
  type RevenueReport,
  type AttentionRow,
} from "./admin";

export {
  createLeadForm,
  listLeadForms,
  countLeadForms,
  getLeadFormById,
  getPublishedLeadForm,
  updateLeadForm,
  setLeadFormStatus,
  submitLead,
  listLeadSubmissions,
  countLeadSubmissions,
  type CreateLeadFormResult,
  type LeadFormInput,
} from "./leadforms";

export {
  listContacts,
  contactStage,
  CRM_STAGES,
  type CrmContact,
  type CrmStage,
} from "./crm";

export {
  getBioLink,
  getPublishedBioLink,
  upsertBioLink,
  recordBioLinkClick,
  getBioLinkClickStats,
  type BioLinkInput,
  type BioClickStat,
} from "./biolink";

export {
  getAnalytics,
  recordPageView,
  getTrafficAnalytics,
  type AnalyticsResult,
  type AnalyticsDay,
  type TrafficResult,
} from "./analytics";
export { logActivity, listActivityLog, countActivityLog } from "./activity";
export {
  createProductReview,
  getBuyerReviewForProduct,
  getProductReviews,
  getProductRatingSummary,
  getProductRatingSummaries,
  createCourseReview,
  getBuyerReviewForCourse,
  getCourseReviews,
  getCourseRatingSummary,
  listTenantReviews,
  countTenantReviews,
  setReviewStatus,
  type CreateReviewResult,
  type RatingSummary,
} from "./reviews";
export {
  createAffiliate,
  setAffiliateStatus,
  deleteAffiliate,
  incrementAffiliateClick,
  listAffiliatesWithStats,
  resolveAffiliateAttribution,
  normaliseAffiliateCode,
  type AffiliateWithStats,
  type NewAffiliate,
  type CreateAffiliateResult,
} from "./affiliates";
export type { AffiliateStatus } from "@prisma/client";
export {
  createUpsell,
  listUpsells,
  countUpsells,
  getUpsellById,
  updateUpsell,
  setUpsellActive,
  deleteUpsell,
  listProductOptionsForUpsell,
  otoOfferPricePaise,
  getActiveOtoForOrder,
  findOtoOrder,
  resolveOtoContext,
  type UpsellInput,
  type SaveUpsellResult,
  type OtoOffer,
  type OtoContext,
} from "./upsells";
export {
  createSequence,
  listSequences,
  getSequenceWithSteps,
  updateSequence,
  setSequenceActive,
  deleteSequence,
  addStep,
  updateStep,
  deleteStep,
  listProductOptionsForSequence,
  enrollInSequences,
  enrollPurchaseFromOrder,
  listDueEnrollments,
  claimEnrollmentAdvance,
  type SequenceInput,
  type StepInput,
  type SaveSequenceResult,
} from "./sequences";
export type { SequenceTrigger, SequenceChannel, EnrollmentStatus } from "@prisma/client";
export {
  seatsRemaining,
  isSoldOut,
  createWorkshop,
  listWorkshops,
  countWorkshops,
  getWorkshopById,
  updateWorkshop,
  setWorkshopStatus,
  listPublishedWorkshops,
  getPublishedWorkshop,
  getPublishedWorkshopById,
  getPublishedWorkshopMeta,
  countWorkshopRegistrations,
  getWorkshopRegistration,
  listRegisteredWorkshops,
  joinFreeWorkshop,
  type CreateWorkshopResult,
} from "./workshop";
export {
  createBookingType,
  listBookingTypes,
  countBookingTypes,
  getBookingTypeById,
  updateBookingType,
  setBookingTypeStatus,
  addBookingSlots,
  listSlots,
  deleteBookingSlot,
  listPublishedBookingTypes,
  getPublishedBookingType,
  getPublishedBookingTypeById,
  getPublishedBookingTypeMeta,
  getOpenSlot,
  getBuyerBookingForType,
  listBuyerBookings,
  listBookingsForType,
  type CreateBookingTypeResult,
} from "./booking";
export type { BookingTypeStatus } from "@prisma/client";
export {
  isCourseComplete,
  issueCertificateIfEligible,
  listBuyerCertificates,
  getCertificateBySerial,
  countCourseCertificates,
  type IssueResult,
} from "./certificates";
export {
  createFileAsset,
  listFileAssets,
  getFileAsset,
  deleteFileAsset,
  tenantStorageBytes,
} from "./media";
export {
  gradeQuiz,
  saveQuiz,
  deleteQuiz,
  getQuizForEditing,
  getQuizForLearner,
  gradeAndRecordAttempt,
  getBestQuizAttempt,
  type QuizQuestionInput,
  type LearnerQuiz,
} from "./quiz";
export type { WorkshopStatus } from "@prisma/client";
export {
  BROADCAST_SEGMENTS,
  normalizeSegment,
  matchesSegment,
  recipientsForSegment,
  segmentCounts,
  listBroadcasts,
  getBroadcast,
  getBroadcastWithRecipients,
  createBroadcast,
  updateBroadcast,
  deleteBroadcast,
  cancelBroadcast,
  queueBroadcast,
  listDueBroadcastRecipients,
  claimBroadcastRecipient,
  finishBroadcastRecipient,
  markBroadcastSending,
  finalizeCompletedBroadcasts,
  listRecentBroadcasts,
  type BroadcastSegment,
} from "./broadcasts";
